<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gwirl</string>
	</array>
	<key>name</key>
	<string>Gwirl (HTML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expressions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#controlflow</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#params</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#imports</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#goblock</string>
        </dict>
		<dict>
			<key>include</key>
			<string>#contentblock</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>goblock</key>
		<dict>
			<key>begin</key>
			<string>\@\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>entity.name.block.gwirl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
                    <string>\@\/\/</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.gwirl</string>
				</dict>
				<dict>
					<key>begin</key>
                    <string>\@\*</string>
					<key>end</key>
					<string>\*\@</string>
					<key>name</key>
					<string>comment.block.gwirl</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\@(([A-Za-z0-9]+)(\.[A-Za-z0-9]+(\([^\)]*\))?)*)</string>
					<key>name</key>
                    <string>variable.mustache</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.go</string>
                        </dict>
                    </array>
				</dict>
			</array>
		</dict>
		<key>imports</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\@import \"[^\"]\"</string>
					<key>name</key>
					<string>import.gwirl</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gwirl</string>
	<key>uuid</key>
	<string>93706aaa-9b66-4e9e-bb64-31a8ffcfb00d</string>
</dict>
</plist>
